version: "3.8"

services:
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build:
      context: .
      dockerfile: docker/neuropowertools/Dockerfile
    command: gunicorn neuropower:wsgi:application --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env.prod

#  nginx:
#    build: docker/nginx
#    ports:
#      - 1337:80
#    depends_on:
#      - web
